url: "https://andrewtbiehl.com"
title: Andrew T. Biehl
author: Andrew T. Biehl
description: "Welcome to my personal website!"
email:
  local_part: hello
  host_name: andrewtbiehl
  top_level_domain: email
github_username:  andrewtbiehl
linkedin_username: andrewtbiehl
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    formatter: HTML
  math_engine: katex
  math_engine_opts:
    output: html
plugins:
  - jekyll-feed
  - jekyll-target-blank
  - jekyll-seo-tag
  - jekyll-figure
header_pages:
  - path: about.md
    title: About
exclude:
  - NOTICE.txt
  - README.md
