url: "https://andrewtbiehl.com"
title: Andrew T. Biehl
author: Andrew T. Biehl
description: "Welcome to my personal website!"
email:
  local_part: hello
  host_name: andrewtbiehl
  top_level_domain: email
github_username:  andrewtbiehl
linkedin_username: andrewtbiehl
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-target-blank
header_pages:
  - about.md
exclude:
  - NOTICE.txt
