url: "https://andrewtbiehl.com"
title: Andrew T. Biehl
author: Andrew T. Biehl
description: "Welcome to my personal website!"
email:
  local_part: hello
  host_name: andrewtbiehl
  top_level_domain: email
github_username:  andrewtbiehl
linkedin_username: andrewtbiehl
markdown: kramdown
kramdown:
  syntax_highlighter: custom_highlighter_delegator
  syntax_highlighter_opts:
    formatter: HTML
    tree_sitter_parsers_dir: _tree_sitter_ruby_adapter/parsers
    css_classes: true
  math_engine: katex
  math_engine_opts:
    output: html
plugins:
  - jekyll-feed
  - jekyll-target-blank
  - jekyll-seo-tag
  - jekyll-figure
header_pages:
  - path: about.md
    title: About
exclude:
  - LICENSE.txt
  - NOTICE.txt
  - README.md
  # Included so that it's ignored when watching for file changes
  # Should not be watched due to the presence of symbolic links
  - _tree_sitter_ruby_adapter
